- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-setuptools
    - python-pip
  when: ansible_python_interpreter is search("^.*python2.*$")

- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3-setuptools
    - python3-pip
  when: ansible_python_interpreter is search("^.*python3.*$")

- name: Install docker python modules
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose=={{ dockerComposeVersion }}
